resources:
  jobs:
    Pipeline_táxis:
      name: pipeline_taxis
      schedule:
        quartz_cron_expression: 34 30 0 * * ?
        timezone_id: UTC
        pause_status: UNPAUSED
      tasks:
        - task_key: download_data
          notebook_task:
            notebook_path: src/ingestion/download_data
            source: GIT
          existing_cluster_id: 0807-181129-8ubhemts
        - task_key: engine_raw
          depends_on:
            - task_key: download_data
          notebook_task:
            notebook_path: src/ingestion/engine_raw
            source: GIT
          existing_cluster_id: 0807-181129-8ubhemts
        - task_key: engine_silver
          depends_on:
            - task_key: engine_raw
          notebook_task:
            notebook_path: src/ingestion/engine_silver
            source: GIT
          existing_cluster_id: 0807-181129-8ubhemts
        - task_key: yellow_taxi_hourly_avg_may_2023
          depends_on:
            - task_key: engine_silver
          notebook_task:
            notebook_path: analysis/yellow_taxi_hourly_avg_may_2023
            source: GIT
          existing_cluster_id: 0807-181129-8ubhemts
        - task_key: yellow_taxi_monthly_avg
          depends_on:
            - task_key: engine_silver
          notebook_task:
            notebook_path: analysis/yellow_taxi_monthly_avg
            source: GIT
          existing_cluster_id: 0807-181129-8ubhemts
      git_source:
        git_url: https://github.com/gabriel-garciae/dl_ny_taxis
        git_provider: gitHub
        git_branch: main
      queue:
        enabled: true
